# Generated by Django 3.1.7 on 2021-04-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksubmit',
            name='Work_Description',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
